---
- name: Gather facts
  hosts: web2
  gather_facts: true

# - name: Configure DB Server
#   hosts: localhost
#   # become: true
#   vars_files:
#     - secrets.yml
#   roles:
#     # - role: mysql-server
#     - role: todolist-db

- name: Configure Web Server
  hosts: web2
  become: true
  #vars_files:
  #  - secrets.yml

  # vars:
  #   moved to group_vars file 

  roles:
    - role: tomcat-server
    - role: todo-webapp


        
